import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/layout/footer";
import Topka from "./components/layout/topka";
import Script from "next/script";
import Rodzic from "./components/home/rodzic";
import RodzicOstatnieRecenzje from "./components/home/ostatnierecenzje";
import MostHated from "./components/home/mosthated";
import BestGames from "./components/home/bestgames";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>

      </head>

      <body className="min-h-full flex flex-col">
   

       <Rodzic />
      <RodzicOstatnieRecenzje />
      <MostHated />
      <BestGames />
      </body>
    </html>
  );
}